### PR TITLE
Added Documentation for create_repo.py

### LINKED ISSUE #62: [GSSOC'23] Documentation for create_repo.py file
I'd like to write the documentation for the `create_repo.py` file. @sahil-sagwekar2652 , please assign this issue to me under GSSOC'23.

### PR DESCRIPTION
**Pull request by SwastikGorai**
closes #62

### CODE REVIEW

**Comment by SwastikGorai** [comment]
@sahil-sagwekar2652 please check this.

**Comment by sahil-sagwekar2652** [comment]
please check the linter output

**Comment by SwastikGorai** [comment]
@sahil-sagwekar2652 fixed linter, flake8

**Review by sahil-sagwekar2652 — APPROVED** [review]
Looks good

**Pull request merged**
