### PR TITLE
Create auto_comment.yml

### PR DESCRIPTION
**Pull request by Harshu467**
Added Auto Comment Feature to Improve Collaboration
Issue Number #88

### CODE REVIEW

**Review by sahil-sagwekar2652 — CHANGES_REQUESTED** [review]
Please reference the issue which was assigned to you and make sure to appropriately document the new features in the README.md file

**Review by sahil-sagwekar2652 — COMMENTED** [review]
Just add a short note in the README no need for so many lines. and reference the issue.

**Comment by Harshu467** [comment]
@sahil-sagwekar2652 , I have updated successfully, Please add labels of gsoc and level

**Comment by Harshu467** [comment]
> Just add a short note in the README no need for so many lines. and reference the issue.

Upadated as told please check and merge and give labels @sahil-sagwekar2652

**Comment by Harshu467** [comment]
This PR has been created at 3rd July still not merge , My request to merge it and give proper labels of level and GSOC @sahil-sagwekar2652

**Comment by sahil-sagwekar2652** [comment]
Please read my above comments and make the changes which I had suggested. I hope you have gone through the CONTRIBUTING.md file.

**Comment by Harshu467** [comment]
Updated as said Please Merge

**Pull request closed without merging**
