### PR TITLE
Create Issue by Python

### PR DESCRIPTION
**Pull request by ayush-09**
Issue No: #58

### CODE REVIEW

**Review by ayush-09 — COMMENTED** [review]
Please Review

**Review by ayush-09 — COMMENTED** [review]
Check Now

**Review by sahil-sagwekar2652 — CHANGES_REQUESTED** [review]
Can you make the output more verbose? I believe there would be more information available in the response object which can be displayed in the output instead of just "Issue created successfully" or "Failed to create issue."

**Review by ayush-09 — COMMENTED** [review]
Please Review

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 Finally updated or any change you want let me know

**Review by sahil-sagwekar2652 — APPROVED** [review]
Looks good

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 Please provide the relevant tag also

**Comment by gurjeetsinghvirdee** [comment]
Hey @sahil-sagwekar2652 
Kindly add the appropriate labels on the PR
either we have to remove this project from gssoc

**Pull request merged**
