### PR TITLE
Create create_build.sh

### LINKED ISSUE #83: Add Build script
**Issue Description:**
Want to add a build script

**Expected Behavior:**
A build script is a helpful addition to a GitHub repository as it resolves several issues related to building or compiling code.

**Labels:**
Additon of script

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added a new build script

Advantages:
A build.sh script automates the process of building the software, making it easier and more efficient. Developers can simply run the script instead of manually executing a series of commands or steps.

Build scripts often include steps to handle dependencies. They can download and install required libraries, frameworks, or external tools automatically, ensuring that all necessary dependencies are in place before building the software.

By using a build.sh script, the build process becomes reproducible. This means that anyone with the script can generate the same build output, ensuring consistency across different machines and enabling collaboration among team members.

closes #83

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check the PR @sahil-sagwekar2652 !!

thanks

**Review by sahil-sagwekar2652 — COMMENTED** [review]
Can you explain the 'mvn' command used in the script? How can a user build apps with different languages?

**Comment by Abhinavcode13** [comment]
Maven is a popular build automation and project management tool primarily used for Java projects, although it can also be used with projects written in other languages.

in this script it performs several tasls such as

mvn clean:  It ensures a clean slate before starting the build process.

mvn package: he packaging step includes compiling the source code, running tests, and creating the output artifact.

mvn test: runs the test cases


JavaScript/Node.js projects, you can use tools like npm or yarn in package.json

they all provide similar functionality as maven

**Comment by Abhinavcode13** [comment]
This is I want to convey hope you get it now @sahil-sagwekar2652

**Review by sahil-sagwekar2652 — COMMENTED** [review]
Doesn't it require a specific file structure? I would request you to write an elaborate README section for this script, explaining how maven is being used and also the dependencies which need to be installed.

**Comment by sahil-sagwekar2652** [comment]
Looks good, rename the file to maven_build.sh

**Comment by Abhinavcode13** [comment]
@sahil-sagwekar2652 done

**Comment by Abhinavcode13** [comment]
@sahil-sagwekar2652 done please merge

**Pull request merged**
