### PR TITLE
#10 Adding an argument for 'description' of the GitHub repository

### PR DESCRIPTION
**Pull request by ashvaneetk**
With the following changes, After parsing the arguments, you can access their values using args.argument_name. For example, args.path will provide the value of the path argument, and args.description will provide the value of the description argument (if provided).

### CODE REVIEW

**Comment by sahil-sagwekar2652** [comment]
Great work @ashvaneetk ! I think you have missed something. 

After adding the argument, you will also have to pass the value in the request payload. Check the 'payload' variable to modify the value for the "description" key.

**Comment by ashvaneetk** [comment]
Thanks for helping me @sahil-sagwekar2652 . It's my first pull request, got to learn a lot being first year undergraduate. I will surely keep your remarks and modify accordingly.

**Comment by sahil-sagwekar2652** [comment]
Please see if you can solve the merge conflict, ping me on the discord channel if you need any help

**Review by sahil-sagwekar2652 — CHANGES_REQUESTED** [review]
Please check the merge conflict. It shouldn't be very difficult. the original 'create_repo' script has been shifted to the 'create_repo.py' file.

**Pull request closed without merging**
