### PR TITLE
Added push_repo python script

### LINKED ISSUE #3: Write a 'push_repo' script
This script will initialize and push an existing local repository to a newly created remote repository of the same name.

### PR DESCRIPTION
**Pull request by shubham-deshmukh**
Hi Team,

I've just submitted a pull request that addresses Issue #3. The changes in this code fix the reported issue and improve the overall functionality of our project. Here's a summary of the modifications made:

1. Used the ```modular approach``` throughout the implementation.
2. parseArgs(): methods parses the arguments
3. pushRepo(): It takes remote URLs as arguments and contains the logic to the push repository.
4. main(): calling method, contains checking of the local git repository and calling pushRepo() functionality.

Modification in the issue statement
> It does not initialize the directory for the local git repository.

Reason: This functionality is already covered in ```create_repo python script```

Please take the time to review the pull request and provide your feedback. I'm open to any suggestions or improvements that would benefit the project. Once the changes are merged, we can close Issue #3 and move forward with the next steps. closes #3 

Thank you for your attention and collaboration!

Best regards,
Shubham

### CODE REVIEW

**Comment by shubham-deshmukh** [comment]
@sahil-sagwekar2652 @iamthecloverly I need your valuable suggestion regarding the following workflow of the create repo

> create_repo python script

@sahil-sagwekar2652 As you contribute this part of the code, as per the code it does the following

1. Create ```remote repository``` using GitHub API
2.  Create/Initialize the ```local repository``` 

> create_repo bash script

Whereas as per @iamthecloverly contribution, bash script does the following

1.  Create ```remote repository``` using GitHub API

There seems to be inconsistency. Please help me understand the issue as the implementation of ```push_repo python script``` is dependent on the 1st workflow (create repo python script).
Above are my observations. Please correct me in case I'm wrong or misunderstood the workflow.

**Comment by shubham-deshmukh** [comment]
Once I have the input from @sahil-sagwekar2652, I will carefully review it and proceed with making the necessary updates accordingly. Thank you for your review and the suggestion you provided. I appreciate your understanding of the situation and your suggestion to improve the clarity of the project's workflow.

**Comment by sahil-sagwekar2652** [comment]
Really commendable work by @shubham-deshmukh @iamthecloverly .  Initially, the create_repo script was indeed meant to create both a local and remote repository and then connect them using "git add remote", if someone could work on adding the code for creating the local repo in the create_repo.sh file, then it would be great.

The code is looking great shubham, if you are up for it, you can add another "description" argument. See pull request #46 for reference.

**Review by sahil-sagwekar2652 — CHANGES_REQUESTED** [review]
The code is looking great Shubham, if you are up for it, you can add another "description" argument. See pull request #46 for reference.

**Comment by sahil-sagwekar2652** [comment]
@shubham-deshmukh It should have precisely the same purpose. When we create a remote repo, we also need to add a description. The description 'made with GitHub api' is currently hardcoded. Instead, it could be asked from the user in the form of an argument.

**Comment by shubham-deshmukh** [comment]
Hi @sahil-sagwekar2652 I have made the changes  as per requested. Following are the changes
1. Added .py extension to the push_repo script to maintain common naming convention throughout the repo. push_repo --> push_repo.py
1. Added description argument as requested.

Please review them. Let me know in case any changes are required else go ahead with the merge procedure.

**Comment by shubham-deshmukh** [comment]
Hi @sahil-sagwekar2652 It's been a while since I have made the requested changes. Can you please look into this PR?

**Review by sahil-sagwekar2652 — APPROVED** [review]
Looks good

**Pull request merged**
